"""make company owner_id nullable

Revision ID: 174a966fdfe3
Revises: fc300741dc17
Create Date: 2026-09-22 13:38:04.459250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174a966fdfe3'
down_revision = 'fc300741dc17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###