"""add_companies_table

Revision ID: 387b8610c2b0
Revises: 76c94c57130d
Create Date: 2026-09-21 13:11:10.161620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387b8610c2b0'
down_revision = '76c94c57130d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###