"""Alignement table commercials

Revision ID: 387ba135128d
Revises: dc85899ca450
Create Date: 2026-08-21 10:34:02.624926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387ba135128d'
down_revision = 'dc85899ca450'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commercials', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'commercials', type_='unique')
    # ### end Alembic commands ###