"""fix nullable and add missing columns

Revision ID: 577bc13bd2b2
Revises: 6087a12828ad
Create Date: 2026-09-22 13:52:25.406711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577bc13bd2b2'
down_revision = '6087a12828ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('companies_owner_id_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key('companies_owner_id_fkey', 'companies', 'users', ['owner_id'], ['id'])
    op.alter_column('companies', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###