"""fix nullable owner_id and add users company_id

Revision ID: 6087a12828ad
Revises: 174a966fdfe3
Create Date: 2026-09-22 13:43:04.900701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6087a12828ad'
down_revision = '174a966fdfe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###