"""add_companies_table

Revision ID: 76c94c57130d
Revises: cc45990b2e2e
Create Date: 2026-09-21 12:44:56.942907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c94c57130d'
down_revision = 'cc45990b2e2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###