"""add company_tender_id to sent_log, make sotradies_id nullable

Revision ID: 9fcd11011821
Revises: 577bc13bd2b2
Create Date: 2026-09-22 14:58:41.555185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fcd11011821'
down_revision = '577bc13bd2b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_log', sa.Column('company_tender_id', sa.Integer(), nullable=True))
    op.alter_column('sent_log', 'sotradies_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.create_index(op.f('ix_sent_log_company_tender_id'), 'sent_log', ['company_tender_id'], unique=False)
    op.create_foreign_key(None, 'sent_log', 'company_tenders', ['company_tender_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sent_log_company_tender_id_fkey", "sent_log", type_="foreignkey")
    op.drop_constraint(None, 'sent_log', type_='foreignkey')
    op.drop_index(op.f('ix_sent_log_company_tender_id'), table_name='sent_log')
    op.alter_column('sent_log', 'sotradies_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('sent_log', 'company_tender_id')
    # ### end Alembic commands ###