"""Ajout table pipeline_log

Revision ID: c14121fe9fc5
Revises: 387ba135128d
Create Date: 2026-08-21 10:48:46.305623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c14121fe9fc5'
down_revision = '387ba135128d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('tender_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_log_created_at'), 'pipeline_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_log_event_type'), 'pipeline_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_pipeline_log_run_id'), 'pipeline_log', ['run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_log_source'), 'pipeline_log', ['source'], unique=False)
    op.create_index(op.f('ix_pipeline_log_tender_id'), 'pipeline_log', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_log_tender_id'), table_name='pipeline_log')
    op.drop_index(op.f('ix_pipeline_log_source'), table_name='pipeline_log')
    op.drop_index(op.f('ix_pipeline_log_run_id'), table_name='pipeline_log')
    op.drop_index(op.f('ix_pipeline_log_event_type'), table_name='pipeline_log')
    op.drop_index(op.f('ix_pipeline_log_created_at'), table_name='pipeline_log')
    op.drop_table('pipeline_log')
    # ### end Alembic commands ###