"""add_companies_table

Revision ID: cc45990b2e2e
Revises: f88bc2870774
Create Date: 2026-09-21 12:40:32.705151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc45990b2e2e'
down_revision = 'f88bc2870774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###