"""add_scraping_sources

Revision ID: f88bc2870774
Revises: abe611a23506
Create Date: 2026-09-21 10:57:16.313210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f88bc2870774'
down_revision = 'abe611a23506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('use_browser', sa.Boolean(), nullable=True))
    op.add_column('scraping_sources', sa.Column('max_pages', sa.Integer(), nullable=True))
    op.add_column('scraping_sources', sa.Column('last_scraped', sa.DateTime(), nullable=True))
    op.add_column('scraping_sources', sa.Column('last_result_count', sa.Integer(), nullable=True))
    op.add_column('scraping_sources', sa.Column('error_count', sa.Integer(), nullable=True))
    op.add_column('scraping_sources', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('scraping_sources', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('scraping_sources', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)
    op.alter_column('scraping_sources', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('scraping_sources', 'actif',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_scraping_sources_id'), 'scraping_sources', ['id'], unique=False)
    op.create_unique_constraint(None, 'scraping_sources', ['url'])
    op.drop_column('scraping_sources', 'derniere_execution')
    op.drop_column('scraping_sources', 'nombre_resultats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_sources', sa.Column('nombre_resultats', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('scraping_sources', sa.Column('derniere_execution', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'scraping_sources', type_='unique')
    op.drop_index(op.f('ix_scraping_sources_id'), table_name='scraping_sources')
    op.alter_column('scraping_sources', 'actif',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('scraping_sources', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('scraping_sources', 'url',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('scraping_sources', 'updated_at')
    op.drop_column('scraping_sources', 'last_error')
    op.drop_column('scraping_sources', 'error_count')
    op.drop_column('scraping_sources', 'last_result_count')
    op.drop_column('scraping_sources', 'last_scraped')
    op.drop_column('scraping_sources', 'max_pages')
    op.drop_column('scraping_sources', 'use_browser')
    # ### end Alembic commands ###