"""add company_id to configuration and commercials, add company_sources and company_tenders

Revision ID: fc300741dc17
Revises: 387b8610c2b0
Create Date: 2026-09-22 13:24:03.585621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc300741dc17'
down_revision = '387b8610c2b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('forme_juridique', sa.String(length=50), nullable=True),
    sa.Column('matricule_fiscal', sa.String(length=50), nullable=True),
    sa.Column('secteur_activite', sa.String(length=255), nullable=True),
    sa.Column('annee_creation', sa.Integer(), nullable=True),
    sa.Column('tranche_effectif', sa.String(length=50), nullable=True),
    sa.Column('responsable_nom', sa.String(length=255), nullable=True),
    sa.Column('responsable_fonction', sa.String(length=255), nullable=True),
    sa.Column('telephone_fixe', sa.String(length=20), nullable=True),
    sa.Column('telephone_mobile', sa.String(length=20), nullable=True),
    sa.Column('site_web', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('code_postal', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('gouvernorat', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('description_activite', sa.Text(), nullable=True),
    sa.Column('produits_services', sa.Text(), nullable=True),
    sa.Column('marques_representees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clients_cibles', sa.Text(), nullable=True),
    sa.Column('zones_intervention', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concurrents', sa.Text(), nullable=True),
    sa.Column('tranche_ca', sa.String(length=50), nullable=True),
    sa.Column('types_offres', sa.Text(), nullable=True),
    sa.Column('budget_min_interet', sa.Float(), nullable=True),
    sa.Column('budget_max_interet', sa.Float(), nullable=True),
    sa.Column('sites_consultes', sa.Text(), nullable=True),
    sa.Column('frequence_alertes', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule_fiscal'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('company_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['scraping_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_id', name='uq_company_source')
    )
    op.create_index(op.f('ix_company_sources_company_id'), 'company_sources', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sources_source_id'), 'company_sources', ['source_id'], unique=False)
    op.create_table('company_tenders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('categorie', sa.String(length=255), nullable=True),
    sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('commercial_id', sa.Integer(), nullable=True),
    sa.Column('acheteur_connu', sa.String(length=10), nullable=True),
    sa.Column('rappel_j3_envoye', sa.DateTime(), nullable=True),
    sa.Column('rappel_j1_envoye', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['commercial_id'], ['commercials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['sotradies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'tender_id', name='uq_company_tender')
    )
    op.create_index(op.f('ix_company_tenders_commercial_id'), 'company_tenders', ['commercial_id'], unique=False)
    op.create_index(op.f('ix_company_tenders_company_id'), 'company_tenders', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_tenders_tender_id'), 'company_tenders', ['tender_id'], unique=False)
    op.add_column('commercials', sa.Column('company_id', sa.Integer(), nullable=True))
    op.drop_constraint('commercials_email_key', 'commercials', type_='unique')
    op.drop_constraint('commercials_nom_key', 'commercials', type_='unique')
    op.create_index(op.f('ix_commercials_company_id'), 'commercials', ['company_id'], unique=False)
    op.create_unique_constraint('uq_commercial_company_email', 'commercials', ['company_id', 'email'])
    op.create_unique_constraint('uq_commercial_company_nom', 'commercials', ['company_id', 'nom'])
    op.create_foreign_key(None, 'commercials', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.add_column('configuration', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_configuration_company_id'), 'configuration', ['company_id'], unique=True)
    op.create_foreign_key(None, 'configuration', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configuration', type_='foreignkey')
    op.drop_index(op.f('ix_configuration_company_id'), table_name='configuration')
    op.drop_column('configuration', 'company_id')
    op.drop_constraint(None, 'commercials', type_='foreignkey')
    op.drop_constraint('uq_commercial_company_nom', 'commercials', type_='unique')
    op.drop_constraint('uq_commercial_company_email', 'commercials', type_='unique')
    op.drop_index(op.f('ix_commercials_company_id'), table_name='commercials')
    op.create_unique_constraint('commercials_nom_key', 'commercials', ['nom'])
    op.create_unique_constraint('commercials_email_key', 'commercials', ['email'])
    op.drop_column('commercials', 'company_id')
    op.drop_index(op.f('ix_company_tenders_tender_id'), table_name='company_tenders')
    op.drop_index(op.f('ix_company_tenders_company_id'), table_name='company_tenders')
    op.drop_index(op.f('ix_company_tenders_commercial_id'), table_name='company_tenders')
    op.drop_table('company_tenders')
    op.drop_index(op.f('ix_company_sources_source_id'), table_name='company_sources')
    op.drop_index(op.f('ix_company_sources_company_id'), table_name='company_sources')
    op.drop_table('company_sources')
    op.drop_table('companies')
    # ### end Alembic commands ###